---
- name: Rename old repos
  shell: mv /etc/apt/sources.list /etc/apt/sources.list.original

- name: Touch File
  shell: touch /etc/apt/sources.list

- name: Install Yandex Repos
  shell: echo '{{ item }}' >> /etc/apt/sources.list
  with_items:
    - deb http://mirror.yandex.ru/ubuntu/ {{os_name}} main restricted
    - deb-src http://mirror.yandex.ru/ubuntu/ {{os_name}} main restricted
    - deb http://mirror.yandex.ru/ubuntu/ {{os_name}}-updates main restricted
    - deb-src http://mirror.yandex.ru/ubuntu/ {{os_name}}-updates main restricted
    - deb http://mirror.yandex.ru/ubuntu/ {{os_name}} universe
    - deb-src http://mirror.yandex.ru/ubuntu/ {{os_name}} universe
    - deb http://mirror.yandex.ru/ubuntu/ {{os_name}}-updates universe
    - deb-src http://mirror.yandex.ru/ubuntu/ {{os_name}}-updates universe
    - deb http://mirror.yandex.ru/ubuntu/ {{os_name}} multiverse
    - deb-src http://mirror.yandex.ru/ubuntu/ {{os_name}} multiverse
    - deb http://mirror.yandex.ru/ubuntu/ {{os_name}}-updates multiverse
    - deb-src http://mirror.yandex.ru/ubuntu/ {{os_name}}-updates multiverse
    - deb http://mirror.yandex.ru/ubuntu/ {{os_name}}-backports main restricted universe multiverse
    - deb-src http://mirror.yandex.ru/ubuntu/ {{os_name}}-backports main restricted universe multiverse

    - deb http://security.ubuntu.com/ubuntu {{os_name}}-security main restricted
    - deb-src http://security.ubuntu.com/ubuntu {{os_name}}-security main restricted
    - deb http://security.ubuntu.com/ubuntu {{os_name}}-security universe
    - deb-src http://security.ubuntu.com/ubuntu {{os_name}}-security universe
    - deb http://security.ubuntu.com/ubuntu {{os_name}}-security multiverse
    - deb-src http://security.ubuntu.com/ubuntu {{os_name}}-security multiverse

- name: Update apt
  apt: update_cache=yes

- name: Generate Locales
  shell: locale-gen {{item}}
  with_items:
   - ru_RU
   - ru_RU.UTF-8

- name: Install System Packages
  apt: pkg={{ item }} state=latest
  with_items:
    - git
    - curl
    - wget
    - zip
    - unzip
    - python-software-properties
    - software-properties-common
    - python-apt

- name: PHP PPA
  apt_repository: repo='ppa:ondrej/php5-5.6'

- name: Redis PPA
  apt_repository: repo='ppa:chris-lea/redis-server'

- name: Update apt
  apt: update_cache=yes

- name: install dependecies
  apt: pkg={{item}}
  with_items:
    - libonig2
    - libqdbm14
    - libedit2
    - libc6
    - libjs-jquery
    - libmysqlclient18
    - libvpx1
    - libgd2-xpm-dev
    - libgearman-dev
    - libxt-dev
    - libvpx-dev
    - libsasl2-dev
    - gearman-tools
    - memcached
    - autoconf
    - automake
    - language-pack-de
    - language-pack-ru
    - gearman-job-server
    

- name: Install Extra Packages
  apt: pkg={{ item }} state=latest
  with_items: sys_packages

