---
- name: MySQL PPA
  apt_repository: repo='ppa:ondrej/mysql-5.6'

- name: Update apt
  apt: update_cache=yes

- name: Install mysql client and server
  apt: pkg={{item}} state=present
  with_items:
    - mysql-client
    - mysql-server

- name: Install python-mysqldb
  apt: pkg=python-mysqldb state=present

- name: create db
  mysql_db: db={{item}} state=present
  with_items: db

- name: create user
  mysql_user: state=present name={{user}} password={{password}}

