---
- name: Clone Repository
  shell: git clone https://github.com/urakozz/php-5.6-precise-debs.git

- name: Clone Repository
  shell: cp -R php-5.6-precise-debs debs

- name: Install libjson
  shell: dpkg -i debs/json-c/*.deb

- name: Install libedit2
  shell: dpkg -i debs/libedit/*.deb

- name: Install libgd3
  shell: dpkg -i debs/libgd2/libgd3*.deb


- name: Install libmemcached11
  shell: dpkg -i --auto-deconfigure debs/libmemcached/{{item}}*.deb
  with_items:
    - libhashkit2
    - libhashkit-dev
    - libmemcached11
    - libmemcachedutil2
    - libmemcached-dev
    - libmemcached-tools

- name: Install gearman
  shell: dpkg -i debs/gearman/*.deb

- name: Install php5
  shell: dpkg -i debs/{{item}}*.deb
  with_items:
    - php5-common
    - php5-dev
    - dh-php5
    - php5-json
    - php5-cli
    - php5-cgi
    - php5-gmp
    - php-pear
    - php5_5
    - libphp5
    - php5-fpm
    - php5-curl
    - php5-intl
    - php5-xsl
    - php5-mysql_
    - php5-readline
    - php5-gd
    - php5-memcache
    - php5-memcached
    - php5-gearman
    - php5-redis
    - php5-mongo

- name: php config updates
  shell: sed -i 's/{{item.search}}/{{item.replace}}/g' {{item.file}}
  with_items:
    - {file: /etc/php5/fpm/php.ini, search: "short_open_tag = Off", replace: "short_open_tag = On"}
    - {file: /etc/php5/cli/php.ini, search: "short_open_tag = Off", replace: "short_open_tag = On"}
    - {file: /etc/php5/fpm/php.ini, search: "memory_limit = 128M",  replace: "memory_limit = -1"}
    - {file: /etc/php5/fpm/php.ini, search: ';default_charset = "UTF-8"', replace: 'default_charset = "UTF-8"'}
    - {file: /etc/php5/cli/php.ini, search: ';default_charset = "UTF-8"', replace: 'default_charset = "UTF-8"'}
    
- name: php fpm restart
  shell: service php5-fpm restart
