---

- name: Install php5
  apt: name={{item}}
  with_items:
    - php5-common
    - php5-json
    - php5-cli
    - php5-cgi
    - php-pear
    - php5-dev
    - php5-fpm
    - php5-curl
    - php5-intl
    - php5-mysql
    - php5-readline
    - php5-gd
    - php5-memcached
    - php5-memcache
    - php5-gearman
    - php5-redis
    - php5-mongo

- name: php config updates
  shell: sed -i 's/{{item.search}}/{{item.replace}}/g' {{item.file}}
  with_items:
    - {file: /etc/php5/fpm/php.ini, search: "short_open_tag = Off", replace: "short_open_tag = On"}
    - {file: /etc/php5/cli/php.ini, search: "short_open_tag = Off", replace: "short_open_tag = On"}
    - {file: /etc/php5/fpm/php.ini, search: "memory_limit = 128M",  replace: "memory_limit = -1"}
    - {file: /etc/php5/fpm/php.ini, search: ';default_charset = "UTF-8"', replace: 'default_charset = "UTF-8"'}
    - {file: /etc/php5/cli/php.ini, search: ';default_charset = "UTF-8"', replace: 'default_charset = "UTF-8"'}
    
- name: php fpm restart
  shell: service php5-fpm restart
