- name: Add Key
  shell: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10

- name: Add repository
  shell: echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list

- name: Update apt
  apt: update_cache=yes

- name: Inatall MongoDB
  apt: name=mongodb-org
  when: travis is not defined