---
- hosts: all
  sudo: true
  vars:
    os_name: trusty
    sys_packages: ["nano"]
  roles:
    - init
    - php
    - composer
    - redis
    - mongodb
    - {role: mysql, db: ["multiship", "robot"], user: root, password: root}
    - {role: nginx, root: /vagrant/frontend/www, server_name: multiship.local}
